onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_TES
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_LUM
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_TRM
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_RGB
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_OHS
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_RE1
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_RE2
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_SHP
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_BLU
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_EMB
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_YCC
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_SOB
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_CGA
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_HSV
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_HSL
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/L_BLU
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/L_AVG
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/L_OBJ
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/L_CGA
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/L_YCC
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/L_SHP
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/L_D1T
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/L_B1T
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/L_HSL
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/L_HIS
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/L_SPC
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/M_SOB_LUM
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/M_SOB_TRM
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/M_SOB_RGB
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/M_SOB_SHP
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/M_SOB_BLU
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/M_SOB_YCC
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/M_SOB_CGA
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/M_SOB_HSV
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/M_SOB_HSL
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_BLUR_CHANNELS
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/F_DITH_CHANNELS
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/img_width
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/img_height
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/adwrWidth
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/addrWidth
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/s_data_width
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/i_data_width
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/clk
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/rst_l
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/txCord
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/iRgb
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/iLumTh
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/iSobelTh
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/iVideoChannel
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/iFilterId
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/iHsvPerCh
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/iYccPerCh
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/iAls
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/iKcoeff
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/oKcoeff
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/edgeValid
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/blur_channels
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/oRgb
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/rgbImageKernel
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/rgbLocFilt
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/rgbLocSynSFilt
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/fRgb
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/sEdgeValid
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/ycbcrValid
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/fRgb1
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/fRgb2
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/fRgb3
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/cgainIoIn
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/sharpIoIn
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/blurIoIn
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/YcbcrIoIn
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/cgainIoOut
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/cgainValidRgb
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/sharpIoOut
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/blurIoOut
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/sharpIodValid
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/blurIodValid
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/YcbcrIoOut
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/YcbcrIoOutSelect
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/blur1vx
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/blur11x
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/blur2vx
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/blur21x
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/blur3vx
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/blur31x
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/ditRgb1vx
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/ditRgb2vx
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/ditRgb3vx
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/rgbSel
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/vhsv
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/vh1s
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/vh2s
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/vh3s
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/rgb_hsvl
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/rgb_histo
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/eObject
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/color_limits
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/valid_vhs
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/dark_ccm
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/light_ccm
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/balance_ccm
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/rgb
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/rgbYcbcr
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/VideoStreamInst/frameProcessInst/FiltersInst/init_channel
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {48 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits us
update
WaveRestoreZoom {0 fs} {1 ps}
