onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/addrWidth
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/adwrWidth
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/BLURE_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/blurRgb
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/blurRgbSync
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/CCGAIN_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/ccmcolor
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/CGAIN_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/clk
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/COHSL_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/colorhsl
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/EMBOS_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/F_RE1_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/F_RE2_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/F_RE3_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/F_RE4_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/F_RE5_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/F_RE6_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/F_RE7_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/F_RE8_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsl_1_range
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsl_1_Syncr
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsl_2_range
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsl_2_Syncr
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsl_3_range
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsl_3_Syncr
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsl_4_range
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsl_4_Syncr
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/HSL_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsll1_range
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsll1_Syncr
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsll2_range
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsll2_Syncr
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsll3_range
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsll3_Syncr
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsll4_range
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hsll4_Syncr
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/hslSyncr
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/HSV_1_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/HSV_2_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/HSV_3_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/HSV_4_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/HSV_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/HSVL1_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/HSVL2_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/HSVL3_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/HSVL4_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/i_data_width
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/iFilterId
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/iKcoeff
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/iLumTh
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/img_height
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/img_width
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/init_channel
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/INRGB_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/iRgb
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/iSobelTh
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/kCoProd
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/oEdgeValid
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/oKcoeff
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/oRgb
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/re1color
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/re2color
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/re3color
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/re4color
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/re5color
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/re6color
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/re7color
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/re8color
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/RGBLP_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/rgbMac1
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/rgbMac2
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/rgbMac3
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/rgbSyncValid
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/RGBTR_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/rst_l
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/s_data_width
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/SHARP_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/SOBEL_FRAME
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/txCord
add wave -noupdate /top/vfp_dut/dutVFP_v1Inst/video_stream_inst/frameProcessInst/FiltersInst/filter_kernel_inst/YCBCR_FRAME
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits us
update
WaveRestoreZoom {0 fs} {1 ps}
