onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/clk
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/i_data_width
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/ifvalid
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/iImageTypeTest
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/ilvalid
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/img_frames_cnt_bmp
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/img_height_bmp
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/img_width_bmp
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/iReadyToRead
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/iRgb
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/m_axis_mm2s_aclk
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/m_axis_mm2s_tdata
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/m_axis_mm2s_tvalid
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/read_bmp
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/reset
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/aclk
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/blue
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/endOfFrame
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/fvalid
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/green
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/lvalid
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/pix_clk
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/red
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/rgb
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/valid
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/xCord
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/yCord
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/dFrameEnable
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/doneTask
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/doneWrite
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/enableWrite
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/end_of_frame
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/f_valid
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/i_count
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/l_valid
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/mm2rgb
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/mm2rgb1Sync
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/mm2rgb2Sync
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/pFileCont
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/pixclk
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/rgbRead
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/txCord
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/valid1Sync
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/valid2ndFrame
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/valid2Sync
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/validFrameRiPulse
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/vFrameSync1Pulse
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/vFrameSync2Pulse
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/vFrameSync3Pulse
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/vFrameSync4Pulse
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/vFrameSync5Pulse
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/vFrameSync6Pulse
add wave -noupdate /top/image_read_dut/imageReadInterfaceInst/wTxCord
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3087827 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits us
update
WaveRestoreZoom {0 fs} {1137891225 fs}
